/**
 * Where the Local network carrier keeps its own files (restore points and the
 * attachments this device has sent or received) — a folder inside the plugin's
 * folder. The real one goes through Obsidian's vault adapter, so it also works
 * with whatever the vault is stored on; tests use an in-memory one.
 */

export interface LanFileStore {
	read(name: string): Promise<Uint8Array | null>;
	write(name: string, data: Uint8Array): Promise<void>;
	remove(name: string): Promise<void>;
	exists(name: string): Promise<boolean>;
	/** File names (not paths) directly inside the store. */
	list(): Promise<string[]>;
}

/** The slice of Obsidian's `DataAdapter` that is used. */
export interface LanAdapterLike {
	exists(path: string): Promise<boolean>;
	mkdir(path: string): Promise<void>;
	readBinary(path: string): Promise<ArrayBuffer>;
	writeBinary(path: string, data: ArrayBuffer): Promise<void>;
	remove(path: string): Promise<void>;
	list(path: string): Promise<{ files: string[]; folders: string[] }>;
}

/** Names are generated by the carrier, but a path must still never leave the folder. */
function safeName(name: string): string {
	if (!/^[A-Za-z0-9._-]+$/.test(name) || name === "." || name === "..") throw new Error(`invalid file name: ${name}`);
	return name;
}

export class AdapterFileStore implements LanFileStore {
	private ready: Promise<void> | null = null;

	constructor(
		private readonly adapter: LanAdapterLike,
		/** A vault-relative folder, e.g. `.obsidian/plugins/yaos/lan/blobs`. */
		private readonly folder: string,
	) {}

	private async ensure(): Promise<void> {
		this.ready ??= (async () => {
			const parts = this.folder.split("/").filter((p) => p.length > 0);
			let path = "";
			for (const part of parts) {
				path = path ? `${path}/${part}` : part;
				if (!(await this.adapter.exists(path))) await this.adapter.mkdir(path);
			}
		})().catch((err: unknown) => {
			this.ready = null;
			throw err;
		});
		return this.ready;
	}

	private path(name: string): string {
		return `${this.folder}/${safeName(name)}`;
	}

	async read(name: string): Promise<Uint8Array | null> {
		await this.ensure();
		const path = this.path(name);
		if (!(await this.adapter.exists(path))) return null;
		return new Uint8Array(await this.adapter.readBinary(path));
	}

	async write(name: string, data: Uint8Array): Promise<void> {
		await this.ensure();
		const copy = new Uint8Array(data.byteLength);
		copy.set(data);
		await this.adapter.writeBinary(this.path(name), copy.buffer);
	}

	async remove(name: string): Promise<void> {
		await this.ensure();
		const path = this.path(name);
		if (await this.adapter.exists(path)) await this.adapter.remove(path);
	}

	async exists(name: string): Promise<boolean> {
		await this.ensure();
		return await this.adapter.exists(this.path(name));
	}

	async list(): Promise<string[]> {
		await this.ensure();
		const listing = await this.adapter.list(this.folder);
		return listing.files.map((f) => f.slice(f.lastIndexOf("/") + 1));
	}
}

/** In-memory store (tests). */
export class MemoryFileStore implements LanFileStore {
	readonly files = new Map<string, Uint8Array>();

	read(name: string): Promise<Uint8Array | null> {
		const found = this.files.get(safeName(name));
		return Promise.resolve(found ? new Uint8Array(found) : null);
	}

	write(name: string, data: Uint8Array): Promise<void> {
		this.files.set(safeName(name), new Uint8Array(data));
		return Promise.resolve();
	}

	remove(name: string): Promise<void> {
		this.files.delete(safeName(name));
		return Promise.resolve();
	}

	exists(name: string): Promise<boolean> {
		return Promise.resolve(this.files.has(safeName(name)));
	}

	list(): Promise<string[]> {
		return Promise.resolve(Array.from(this.files.keys()));
	}
}

export async function sha256Hex(data: Uint8Array): Promise<string> {
	const copy = new Uint8Array(data.byteLength);
	copy.set(data);
	const digest = await crypto.subtle.digest("SHA-256", copy.buffer);
	return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, "0")).join("");
}
