/**
 * Google Drive setup wizard: the step flow, creating and joining a vault
 * against the fake Drive, what is saved and when, and what the screens say.
 */

import { DriveError } from "../../src/drive-carrier/driveApi";
import { GoogleAuthError, type DeviceSignInResult, type GoogleClient } from "../../src/drive-carrier/googleAuth";
import type { SignInUi } from "../../src/drive-carrier/signIn";
import { createVault, checkVaultForJoin, TEST_FILE_NAME } from "../../src/drive-carrier/wizard/driveSetup";
import { BUNDLED_GOOGLE_CLIENT } from "../../src/drive-carrier/wizard/bundledClient";
import { buildScreen, type Screen } from "../../src/drive-carrier/wizard/screens";
import { decodeSetupCode, encodeSetupCode } from "../../src/drive-carrier/wizard/setupCode";
import {
	WizardController,
	stepsFor,
	type FinishResult,
	type StepId,
	type WizardDeps,
	type WizardSettings,
	type WizardSettingsPatch,
} from "../../src/drive-carrier/wizard/wizardController";
import { FakeDrive } from "../mocks/fakeDrive";
import { suite } from "../harness.ts";

const s = suite("drive-carrier-wizard-flow");

const OWN_ID = "111111111-ownclient.apps.googleusercontent.com";
const OWN_SECRET = "GOCSPX-ownsecret0123456789";
const BUNDLED: GoogleClient = { clientId: "999999999-bundled.apps.googleusercontent.com", clientSecret: "GOCSPX-bundledsecret0123" };
const FIRST_VAULT = "vaultAAAAAAAAAAAAAAAAAA";

interface Rig {
	c: WizardController;
	drive: FakeDrive;
	settings: WizardSettings;
	applied: WizardSettingsPatch[];
	copied: string[];
	opened: string[];
	signInCalls: GoogleClient[];
	finishCalls: number;
	closed: number;
	/** Make the next sign-in fail, or wait until released. */
	failSignIn: GoogleAuthError | null;
	gate: { release: () => void; promise: Promise<void> } | null;
	finishResult: FinishResult;
	/** Requests the wizard sent through `http` (only the easy sign-in service is answered). */
	httpCalls: { url: string; body: string }[];
	hostedReply: { status: number; json: Record<string, unknown> } | "offline";
}

const HOSTED_URL = "https://hosted.test/api/access";
const GOOD_TOKEN = "1//0gHostedRefreshTokenForTests-0123456789";

function makeRig(options: { bundled?: boolean; settings?: Partial<WizardSettings>; drive?: FakeDrive; vaultIds?: string[]; savedEndpoint?: boolean; realApi?: boolean } = {}): Rig {
	const drive = options.drive ?? new FakeDrive();
	const settings: WizardSettings = { vaultId: "autoGeneratedUnusedId000", ...options.settings };
	const vaultIds = [...(options.vaultIds ?? [FIRST_VAULT])];
	const rig: Rig = {
		drive, settings, applied: [], copied: [], opened: [], signInCalls: [], finishCalls: 0, closed: 0,
		failSignIn: null, gate: null, finishResult: "started", c: null as never, // assigned right below, once the controller exists
		httpCalls: [], hostedReply: { status: 200, json: { access_token: "hosted-access", expires_in: 3600 } },
	};
	const deps: WizardDeps = {
		http: async (req) => {
			rig.httpCalls.push({ url: req.url, body: typeof req.body === "string" ? req.body : "" });
			if (req.url === (options.savedEndpoint ? rig.settings.driveHostedUrl?.trim() : HOSTED_URL)) {
				if (rig.gate) await rig.gate.promise;
				if (rig.hostedReply === "offline") throw new Error("offline");
				return { status: rig.hostedReply.status, body: new TextEncoder().encode(JSON.stringify(rig.hostedReply.json)) };
			}
			if (options.realApi && req.url.startsWith("https://www.googleapis.com/drive/v3/files") && req.method === "GET") {
				return { status: 200, body: new TextEncoder().encode(JSON.stringify({ files: [] })) };
			}
			throw new Error("the wizard test must not touch real HTTP");
		},
		hostedUrl: options.savedEndpoint ? undefined : HOSTED_URL,
		sleep: async () => undefined,
		getSettings: () => rig.settings,
		applySettings: async (patch) => {
			rig.applied.push(patch);
			Object.assign(rig.settings, {
				carrier: patch.carrier, vaultId: patch.vaultId, driveClientId: patch.driveClientId,
				driveClientSecret: patch.driveClientSecret, driveRefreshToken: patch.driveRefreshToken,
				driveEncryptionPassphrase: patch.driveEncryptionPassphrase,
			});
		},
		newVaultId: () => vaultIds.shift() ?? `generated${Math.random().toString(36).slice(2)}0000000`,
		bundledClient: options.bundled ? BUNDLED : null,
		copyText: async (text) => { rig.copied.push(text); },
		openUrl: (url) => { rig.opened.push(url); },
		finishSetup: async () => { rig.finishCalls++; return rig.finishResult; },
		kdfIterations: 1000,
		signIn: async (client: GoogleClient, ui: SignInUi): Promise<DeviceSignInResult> => {
			rig.signInCalls.push(client);
			ui.showCode({ deviceCode: "dev", userCode: "ABCD-EFGH", verificationUrl: "https://www.google.com/device", expiresInSeconds: 1800, intervalSeconds: 5 });
			if (rig.gate) await rig.gate.promise;
			if (ui.isCancelled()) throw new GoogleAuthError("Sign-in was cancelled.", "cancelled", false);
			if (rig.failSignIn) {
				const err = rig.failSignIn;
				rig.failSignIn = null;
				throw err;
			}
			return { refreshToken: `refresh-${rig.signInCalls.length}`, accessToken: "access", expiresInSeconds: 3600 };
		},
		makeApi: options.realApi ? undefined : () => drive.client(),
		onClose: () => { rig.closed++; },
	};
	rig.c = new WizardController(deps);
	return rig;
}

function gate(): { release: () => void; promise: Promise<void> } {
	let release = (): void => undefined;
	const promise = new Promise<void>((resolve) => { release = resolve; });
	return { release, promise };
}

async function toPaste(rig: Rig): Promise<void> {
	await rig.c.next();
	rig.c.choosePath("new");
	await tick();
	rig.c.chooseClient("own");
	await tick();
	for (let i = 0; i < 5; i++) await rig.c.next();
}

async function tick(): Promise<void> {
	for (let i = 0; i < 20; i++) await Promise.resolve();
}

/** Own client, encrypted vault, all the way to the code screen. */
async function createOwnVault(rig: Rig, passphrase = "a long passphrase"): Promise<void> {
	await toPaste(rig);
	rig.c.setFieldByKey("clientId", OWN_ID);
	rig.c.setFieldByKey("clientSecret", OWN_SECRET);
	await rig.c.next(); // -> sign in (and on to encryption)
	rig.c.setFieldByKey("passphrase", passphrase);
	rig.c.setFieldByKey("passphraseConfirm", passphrase);
	rig.c.setFieldByKey("riskAccepted", true);
	await rig.c.next(); // -> create
}

function allScreens(rig: Rig): Screen[] {
	return [buildScreen(rig.c)];
}

s.section("Test 1: the steps for each choice");
{
	const base = makeRig().c.state.draft;
	const own = stepsFor({ ...base, path: "new", clientMode: "own" }, { alreadySetUp: false });
	s.check(own.join() === "welcome,choose,client,guide-project,guide-api,guide-consent,guide-client,guide-publish,paste,signin,encryption,create,code,done", `new vault, own client (${own.join()})`);
	const built = stepsFor({ ...base, path: "new", clientMode: "bundled" }, { alreadySetUp: false });
	s.check(built.join() === "welcome,choose,client,signin,encryption,create,code,done", `new vault, built-in client (${built.join()})`);
	const easy = stepsFor({ ...base, path: "new", clientMode: "hosted" }, { alreadySetUp: false });
	s.check(easy.join() === "welcome,choose,client,hosted-token,signin,encryption,create,code,done", `new vault, easy sign-in (${easy.join()})`);
	const join = stepsFor({ ...base, path: "join", clientMode: "own" }, { alreadySetUp: false });
	s.check(join.join() === "welcome,choose,join-code,signin,join-check,done", `join (${join.join()})`);
	const joinEasy = stepsFor({ ...base, path: "join", clientMode: "hosted" }, { alreadySetUp: false });
	s.check(joinEasy.join() === "welcome,choose,join-code,hosted-token,signin,join-check,done", `join, easy sign-in (${joinEasy.join()})`);
	const again = stepsFor({ ...base, path: "new", clientMode: "bundled" }, { alreadySetUp: true });
	s.check(again.join() === "welcome,choose,client,existing,signin,encryption,create,code,done", "a device that is already set up gets a warning step");
	const againEasy = stepsFor({ ...base, path: "new", clientMode: "hosted" }, { alreadySetUp: true });
	s.check(againEasy.join() === "welcome,choose,client,existing,hosted-token,signin,encryption,create,code,done", "the warning comes before the sign-in code is asked for");
	s.check(base.clientMode === "hosted", "the easy sign-in is the default choice");
	s.check(BUNDLED_GOOGLE_CLIENT === null || (BUNDLED_GOOGLE_CLIENT.clientId.endsWith(".apps.googleusercontent.com") && BUNDLED_GOOGLE_CLIENT.clientSecret.length > 10), "the built-in client is either not set or looks valid");
}

s.section("Test 2: a new vault with the user's own client, encrypted");
{
	const rig = makeRig();
	s.check(rig.c.state.step === "welcome", "starts at the welcome screen");
	s.check(buildScreen(rig.c).progress === null, "no progress on the welcome screen");
	await rig.c.next();
	s.check(rig.c.state.step === "choose", "then the choice");
	rig.c.choosePath("new");
	await tick();
	s.check(rig.c.state.step === "client", "then how to sign in");
	rig.c.chooseClient("own");
	await tick();
	s.check(rig.c.state.step === "guide-project", "own client: the guide starts");
	s.check(buildScreen(rig.c).progress === "Step 4 of 14", `progress counts all steps (${String(buildScreen(rig.c).progress)})`);
	s.check(rig.drive.calls.createFolder === 0 && rig.drive.calls.findFolders === 0 && rig.applied.length === 0, "nothing on Drive and nothing saved while reading the guide");
	for (let i = 0; i < 5; i++) await rig.c.next();
	s.check(rig.c.state.step === "paste", "five guide screens, then the paste screen");
	s.check(!rig.c.canNext() && rig.c.blocker() !== null, "cannot continue without client details");
	rig.c.setFieldByKey("clientId", "nonsense");
	s.check(buildScreen(rig.c).fields[0]?.problem !== null, "a wrong client ID shows a problem under the field");
	rig.c.setFieldByKey("clientId", OWN_ID);
	rig.c.setFieldByKey("clientSecret", OWN_SECRET);
	s.check(rig.c.canNext(), "valid details let it continue");
	await rig.c.next();
	s.check(rig.signInCalls.length === 1 && rig.signInCalls[0]?.clientId === OWN_ID && rig.signInCalls[0]?.clientSecret === OWN_SECRET, "signs in with the pasted client");
	s.check(rig.c.state.step === "encryption", "after sign-in it moves on by itself");
	s.check(rig.applied.length === 0 && rig.drive.calls.findFolders === 0, "still nothing saved and nothing on Drive after sign-in");
	s.check(!rig.c.canNext(), "encryption: a passphrase is required by default");
	rig.c.setFieldByKey("passphrase", "a long passphrase");
	rig.c.setFieldByKey("passphraseConfirm", "a different one");
	s.check(!rig.c.canNext(), "a different confirmation blocks");
	rig.c.setFieldByKey("passphraseConfirm", "a long passphrase");
	s.check(!rig.c.canNext() && String(rig.c.blocker()).includes("Tick"), "the risk box must be ticked");
	rig.c.setFieldByKey("riskAccepted", true);
	await rig.c.next();
	s.check(rig.c.state.step === "create" && rig.c.committed, "the vault is created");
	s.check(rig.applied.length === 1, "settings are saved exactly once, at the end");
	const patch = rig.applied[0];
	s.check(patch?.carrier === "drive" && patch.vaultId === FIRST_VAULT && patch.driveClientId === OWN_ID && patch.driveClientSecret === OWN_SECRET && patch.driveRefreshToken === "refresh-1" && patch.driveEncryptionPassphrase === "a long passphrase", "the saved settings are the chosen ones");
	s.check(patch?.vaultId !== "autoGeneratedUnusedId000", "a fresh vault ID, not the unused automatic one");
	const names = rig.drive.namesIn(`YAOS ${FIRST_VAULT}`);
	s.check(names.join() === "meta.json", `the folder holds only meta.json (${names.join()})`);
	s.check(!names.includes(TEST_FILE_NAME), "the test file was removed");
	const meta = JSON.parse(new TextDecoder().decode(rig.drive.filesIn(`YAOS ${FIRST_VAULT}`)[0]?.data ?? new Uint8Array())) as { encryption?: unknown; schema?: number };
	s.check(meta.schema === 1 && meta.encryption !== undefined, "meta.json says encrypted, layout 1");
	s.check(rig.c.state.checklist.length === 5 && rig.c.state.checklist.every((x) => x.status === "done"), "all five checks passed");
	s.check(!rig.c.canBack(), "after the vault exists, Back is not offered");
	const code = rig.c.state.setupCode ?? "";
	const decoded = decodeSetupCode(code);
	s.check(decoded.ok && decoded.content.vaultId === FIRST_VAULT && decoded.content.clientId === OWN_ID && decoded.content.passphrase === "a long passphrase" && decoded.content.encrypted && !decoded.content.bundledClient, "the setup code describes this vault");
	s.check(!JSON.stringify(decoded).includes("refresh-1"), "the code has no sign-in token");
	await rig.c.next();
	s.check(rig.c.state.step === "code", "the code screen follows");
	await rig.c.copySetupCode();
	s.check(rig.copied[0] === code && rig.c.state.copied, "Copy puts the code on the clipboard");
	rig.c.setFieldByKey("includePassphrase", false);
	const lean = decodeSetupCode(rig.c.state.setupCode ?? "");
	s.check(lean.ok && lean.content.passphrase === "" && lean.content.encrypted, "unticking 'include the passphrase' removes it from the code");
	rig.c.setFieldByKey("includePassphrase", true);
	await rig.c.next();
	s.check(rig.c.state.step === "done" && rig.c.state.result === "started" && rig.finishCalls === 1, "finishing starts sync once");
}

s.section("Test 3: the built-in client");
{
	const rig = makeRig({ bundled: true });
	await rig.c.next();
	rig.c.choosePath("new");
	await tick();
	s.check(rig.c.state.step === "client", "a choice screen first");
	s.check(buildScreen(rig.c).buttons.some((b) => b.action === "client-bundled") && buildScreen(rig.c).buttons.some((b) => b.action === "client-own"), "both ways are offered");
	rig.c.chooseClient("bundled");
	await tick();
	s.check(rig.signInCalls.length === 1 && rig.signInCalls[0]?.clientId === BUNDLED.clientId && rig.signInCalls[0]?.clientSecret === BUNDLED.clientSecret, "signs in with the built-in client, no guide, no pasting");
	s.check(rig.c.state.step === "encryption", "straight on to encryption");
	rig.c.setFieldByKey("encrypt", false);
	s.check(rig.c.canNext(), "encryption can be switched off");
	s.check(buildScreen(rig.c).body.some((b) => b.kind === "note" && /anyone who can open your Google Drive/.test(b.text)), "and then it warns who can read the notes");
	await rig.c.next();
	s.check(rig.applied[0]?.driveEncryptionPassphrase === "" && rig.applied[0]?.driveClientId === BUNDLED.clientId, "saved without a passphrase, with the built-in client");
	const meta = JSON.parse(new TextDecoder().decode(rig.drive.filesIn(`YAOS ${FIRST_VAULT}`)[0]?.data ?? new Uint8Array())) as { encryption?: unknown };
	s.check(meta.encryption === undefined, "meta.json says not encrypted");
	const code = decodeSetupCode(rig.c.state.setupCode ?? "");
	s.check(code.ok && code.content.bundledClient && !code.content.encrypted, "the code says built-in client, not encrypted");

	const own = makeRig({ bundled: true });
	await own.c.next();
	own.c.choosePath("new");
	await tick();
	own.c.chooseClient("own");
	await tick();
	s.check(own.c.state.step === "guide-project", "choosing 'my own client' shows the guide");
}

s.section("Test 4: cancel and back change nothing");
{
	const rig = makeRig();
	await toPaste(rig);
	rig.c.setFieldByKey("clientId", OWN_ID);
	rig.c.setFieldByKey("clientSecret", OWN_SECRET);
	rig.c.cancel();
	s.check(rig.closed === 1 && rig.applied.length === 0 && rig.drive.folders.size === 0 && rig.drive.calls.findFolders === 0, "cancel before sign-in: nothing saved, nothing on Drive");

	const rig2 = makeRig();
	await createOwnVault(rig2).then(() => undefined);
	const rig3 = makeRig();
	await toPaste(rig3);
	rig3.c.setFieldByKey("clientId", OWN_ID);
	rig3.c.setFieldByKey("clientSecret", OWN_SECRET);
	await rig3.c.next();
	s.check(rig3.c.state.step === "encryption", "signed in, on the encryption screen");
	rig3.c.cancel();
	s.check(rig3.applied.length === 0 && rig3.drive.folders.size === 0, "cancel after sign-in: still nothing saved, no folder made");

	const rig4 = makeRig();
	await toPaste(rig4);
	s.check(rig4.c.canBack(), "back is offered on a guide screen");
	await rig4.c.back();
	s.check(rig4.c.state.step === "guide-publish", "back goes one step");
	await rig4.c.next();
	s.check(rig4.c.state.step === "paste", "forward again");
	rig4.c.setFieldByKey("clientId", OWN_ID);
	rig4.c.setFieldByKey("clientSecret", OWN_SECRET);
	await rig4.c.next();
	await rig4.c.back();
	s.check(rig4.c.state.step === "paste", "back from encryption goes to the paste screen");
	await rig4.c.next();
	s.check(rig4.signInCalls.length === 1 && rig4.c.state.step === "encryption", "going forward again does not ask Google a second time");
	rig4.c.setFieldByKey("clientId", "222222222-another.apps.googleusercontent.com");
	await rig4.c.back();
	await rig4.c.next();
	s.check(rig4.signInCalls.length === 2 && rig4.signInCalls[1]?.clientId === "222222222-another.apps.googleusercontent.com", "a different client does need a new sign-in");
}

s.section("Test 5: leaving the sign-in step while Google is waiting");
{
	const rig = makeRig();
	await toPaste(rig);
	rig.c.setFieldByKey("clientId", OWN_ID);
	rig.c.setFieldByKey("clientSecret", OWN_SECRET);
	rig.gate = gate();
	const pending = rig.c.next();
	await tick();
	s.check(rig.c.state.step === "signin" && rig.c.state.signIn?.userCode === "ABCD-EFGH", "the sign-in code is shown while waiting");
	const screen = buildScreen(rig.c);
	s.check(screen.body.some((b) => b.kind === "code" && b.text === "ABCD-EFGH") && screen.buttons.some((b) => b.action === "copy-signin-code"), "the screen shows the code and a Copy button");
	s.check(screen.body.some((b) => b.kind === "link" && b.url === "https://www.google.com/device"), "and a button for google.com/device");
	s.check(!rig.c.canBack() && rig.c.state.busy !== null, "no Back while busy");
	rig.c.cancel();
	rig.gate.release();
	await pending;
	s.check(rig.c.state.step === "signin" && rig.applied.length === 0 && rig.c.state.draft.refreshToken === "", "a cancelled sign-in saves nothing and does not move on");
}

s.section("Test 6: sign-in problems are explained, and Try again works");
{
	const rig = makeRig();
	await toPaste(rig);
	rig.c.setFieldByKey("clientId", OWN_ID);
	rig.c.setFieldByKey("clientSecret", OWN_SECRET);
	rig.failSignIn = new GoogleAuthError("bad", "invalid_client", false);
	await rig.c.next();
	s.check(rig.c.state.step === "signin" && /client ID or client secret/.test(String(rig.c.state.error)), "invalid client: the message names the client details");
	const screen = buildScreen(rig.c);
	s.check(screen.buttons.some((b) => b.action === "retry") && screen.error === rig.c.state.error, "the screen shows the message and Try again");
	await rig.c.retry();
	s.check(rig.c.state.step === "encryption" && rig.c.state.error === null, "Try again signs in and moves on");

	const rig2 = makeRig();
	await toPaste(rig2);
	rig2.c.setFieldByKey("clientId", OWN_ID);
	rig2.c.setFieldByKey("clientSecret", OWN_SECRET);
	rig2.failSignIn = new GoogleAuthError("declined", "access_denied", false);
	await rig2.c.next();
	s.check(/Publish app/.test(String(rig2.c.state.error)), "declined: points to publishing the app");
}

s.section("Test 7: creating the vault fails clearly and can be retried");
{
	const rig = makeRig();
	rig.drive.failNext("createFile", 403, 1);
	await createOwnVault(rig);
	s.check(rig.c.state.step === "create" && rig.applied.length === 0, "a failed write saves nothing");
	s.check(rig.c.state.checklist.some((x) => x.status === "failed") && rig.c.state.checklist[0]?.status === "done", "the checklist shows where it stopped");
	s.check(/Google Drive refused access/.test(String(rig.c.state.error)) || /Drive API/.test(String(rig.c.state.error)), `403 is explained (${String(rig.c.state.error)})`);
	s.check(!rig.c.canNext() && buildScreen(rig.c).buttons.some((b) => b.action === "retry"), "Next is blocked and Try again is offered");
	await rig.c.retry();
	s.check(rig.applied.length === 1 && rig.c.committed && rig.c.state.error === null, "Try again completes the setup");
	s.check(rig.drive.namesIn(`YAOS ${FIRST_VAULT}`).join() === "meta.json", "and leaves no stray file");

	const off = makeRig();
	off.drive.offline = true;
	await createOwnVault(off);
	s.check(/No connection/.test(String(off.c.state.error)) && off.applied.length === 0, "offline: a clear message, nothing saved");

	const api = makeRig();
	api.drive.failNext("findFolders", 403, 1);
	await createOwnVault(api);
	s.check(api.applied.length === 0 && String(api.c.state.error).length > 20, "403 on the first call fails before anything is created");
}

s.section("Test 8: joining with a setup code");
{
	const first = makeRig();
	await createOwnVault(first);
	const code = first.c.state.setupCode ?? "";

	const rig = makeRig({ drive: first.drive, settings: { vaultId: "someOtherVaultIdXXXXXXX" } });
	await rig.c.next();
	rig.c.choosePath("join");
	await tick();
	s.check(rig.c.state.step === "join-code", "the join path asks for the code");
	s.check(!rig.c.canNext(), "cannot continue without a code");
	rig.c.setFieldByKey("setupCodeText", code.slice(0, 30));
	s.check(!rig.c.canNext() && String(rig.c.blocker()).length > 10, "a cut-off code explains itself");
	rig.c.setFieldByKey("setupCodeText", `\n  ${code}  \n`);
	s.check(rig.c.canNext(), "the full code (with stray spaces) is accepted");
	s.check(rig.c.previewJoinCode()?.vaultId === FIRST_VAULT && rig.c.previewJoinCode()?.encrypted === true, "the screen can show which vault the code is for");
	await rig.c.next();
	s.check(rig.signInCalls[0]?.clientId === OWN_ID, "signs in with the client from the code");
	s.check(rig.c.state.step === "join-check" && rig.c.state.joinCheck?.status === "ok", "the vault is found and the passphrase fits");
	s.check(rig.applied.length === 1 && rig.applied[0]?.vaultId === FIRST_VAULT && rig.applied[0]?.driveEncryptionPassphrase === "a long passphrase" && rig.applied[0]?.driveRefreshToken === "refresh-1", "this device's own sign-in and the code's details are saved");
	s.check(rig.drive.namesIn(`YAOS ${FIRST_VAULT}`).join() === "meta.json", "joining wrote nothing to Drive");
	await rig.c.next();
	s.check(rig.c.state.step === "done" && rig.finishCalls === 1, "finish");

	// a code made without the passphrase
	const lean = makeRig({ drive: first.drive });
	await lean.c.next();
	lean.c.choosePath("join");
	await tick();
	lean.c.setFieldByKey("setupCodeText", encodeSetupCode({ vaultId: FIRST_VAULT, clientId: OWN_ID, clientSecret: OWN_SECRET, bundledClient: false, passphrase: "", encrypted: true }));
	await lean.c.next();
	s.check(lean.c.state.joinCheck?.status === "needs-passphrase" && lean.applied.length === 0, "no passphrase in the code: it asks for one and saves nothing");
	const prompt = buildScreen(lean.c);
	s.check(prompt.fields.some((f) => f.key === "joinPassphrase") && prompt.buttons.some((b) => b.action === "retry"), "the screen has a passphrase box and Check again");
	lean.c.setFieldByKey("joinPassphrase", "not the passphrase");
	await lean.c.retry();
	s.check(lean.c.state.joinCheck?.status === "wrong-passphrase" && lean.applied.length === 0, "a wrong passphrase is named and saves nothing");
	s.check(buildScreen(lean.c).fields.some((f) => f.key === "joinPassphrase"), "and the box stays so it can be fixed");
	lean.c.setFieldByKey("joinPassphrase", "a long passphrase");
	await lean.c.retry();
	s.check(lean.c.state.joinCheck?.status === "ok" && lean.applied.length === 1 && lean.applied[0]?.driveEncryptionPassphrase === "a long passphrase", "the right passphrase joins");
}

s.section("Test 9: joining by hand, and joining problems");
{
	const first = makeRig({ bundled: true });
	await first.c.next();
	first.c.choosePath("new");
	await tick();
	first.c.chooseClient("bundled");
	await tick();
	first.c.setFieldByKey("encrypt", false);
	await first.c.next();

	const hand = makeRig({ bundled: true, drive: first.drive });
	await hand.c.next();
	hand.c.choosePath("join");
	await tick();
	hand.c.setFieldByKey("manualJoin", true);
	s.check(!hand.c.canNext(), "by hand: the vault ID is required");
	hand.c.setFieldByKey("vaultId", "bad id");
	s.check(!hand.c.canNext(), "a bad vault ID is refused");
	hand.c.setFieldByKey("vaultId", FIRST_VAULT);
	s.check(hand.c.canNext(), "with a built-in client the Google fields can stay empty");
	await hand.c.next();
	s.check(hand.signInCalls[0]?.clientId === BUNDLED.clientId, "then the built-in client is used");
	s.check(hand.c.state.joinCheck?.status === "ok" && hand.applied.length === 1 && hand.applied[0]?.driveEncryptionPassphrase === "", "an unencrypted vault is joined");

	const nothing = makeRig({ drive: new FakeDrive() });
	await nothing.c.next();
	nothing.c.choosePath("join");
	await tick();
	nothing.c.setFieldByKey("manualJoin", true);
	nothing.c.setFieldByKey("vaultId", "doesNotExistAnywhere1");
	s.check(!nothing.c.canNext(), "without a built-in client the Google fields are required");
	nothing.c.setFieldByKey("clientId", OWN_ID);
	nothing.c.setFieldByKey("clientSecret", OWN_SECRET);
	await nothing.c.next();
	s.check(nothing.c.state.joinCheck?.status === "not-found" && nothing.applied.length === 0, "an unknown vault: not found, nothing saved");
	s.check(/same Google account and the same Google client/.test(JSON.stringify(buildScreen(nothing.c).body)), "and the screen says what to check");
	s.check(!nothing.c.committed && nothing.c.canBack(), "Back is still possible");

	const plainVault = makeRig({ drive: first.drive, bundled: true });
	await plainVault.c.next();
	plainVault.c.choosePath("join");
	await tick();
	plainVault.c.setFieldByKey("manualJoin", true);
	plainVault.c.setFieldByKey("vaultId", FIRST_VAULT);
	plainVault.c.setFieldByKey("passphrase", "something");
	await plainVault.c.next();
	s.check(plainVault.c.state.joinCheck?.status === "not-encrypted" && plainVault.applied.length === 0, "a passphrase for a vault that is not encrypted is named");
	const clearButton = buildScreen(plainVault.c).buttons.find((b) => b.action === "clear-join-passphrase");
	s.check(!!clearButton, "and offers to clear it");
	plainVault.c.setJoinPassphrase("");
	await plainVault.c.retry();
	s.check(plainVault.c.state.joinCheck?.status === "ok", "cleared: it joins");

	const layout = new FakeDrive();
	const api = layout.client();
	const folder = await api.createFolder(`YAOS ${FIRST_VAULT}`);
	await api.createFile(folder.id, "meta.json", new TextEncoder().encode(JSON.stringify({ schema: 99 })));
	const r = await checkVaultForJoin(api, FIRST_VAULT, "");
	s.check(r.status === "other-layout" && r.found === "99", "another layout is named, not guessed at");
	const empty = new FakeDrive();
	const emptyApi = empty.client();
	await emptyApi.createFolder(`YAOS ${FIRST_VAULT}`);
	s.check((await checkVaultForJoin(emptyApi, FIRST_VAULT, "")).status === "not-found", "a folder without meta.json is not a vault");
	s.check(empty.files.size === 0, "checking a vault never writes");
}

s.section("Test 10: a device that is already set up");
{
	const rig = makeRig({
		settings: { carrier: "drive", vaultId: "existingVaultIdXXXXXXXX", driveClientId: OWN_ID, driveClientSecret: OWN_SECRET, driveRefreshToken: "old" },
		vaultIds: ["brandNewVaultIdYYYYYYYY"],
	});
	s.check(rig.c.alreadySetUp, "recognised as already set up");
	await rig.c.next();
	rig.c.choosePath("new");
	await tick();
	rig.c.chooseClient("own");
	await tick();
	for (let i = 0; i < 5; i++) await rig.c.next();
	rig.c.setFieldByKey("clientId", OWN_ID);
	rig.c.setFieldByKey("clientSecret", OWN_SECRET);
	await rig.c.next();
	s.check(rig.c.state.step === "existing", "a warning step comes before sign-in");
	s.check(buildScreen(rig.c).body.some((b) => b.kind === "p" && b.text.includes("existingVaultIdXXXXXXXX")) && buildScreen(rig.c).body.some((b) => b.kind === "note" && /stays in Google Drive/.test(b.text)), "it names the current vault and says the old one stays on Drive");
	s.check(!rig.c.canNext(), "it must be acknowledged");
	rig.c.setFieldByKey("existingAccepted", true);
	await rig.c.next();
	rig.c.setFieldByKey("encrypt", false);
	await rig.c.next();
	s.check(rig.applied[0]?.vaultId === "brandNewVaultIdYYYYYYYY", "a new vault ID is used, never the old vault's folder");
	s.check(rig.drive.folders.size === 1 && rig.drive.namesIn("YAOS existingVaultIdXXXXXXXX").length === 0, "the old vault's folder is not touched");
}

s.section("Test 11: finishing");
{
	const reload = makeRig();
	reload.finishResult = "reload";
	await createOwnVault(reload);
	await reload.c.next();
	await reload.c.next();
	const screen = buildScreen(reload.c);
	s.check(reload.c.state.result === "reload" && screen.buttons.some((b) => b.action === "reload"), "when sync cannot start now, a Reload button is offered");
	reload.c.reload();
	s.check(true, "reload without a handler does not throw");

	const throwing = makeRig();
	await createOwnVault(throwing);
	await throwing.c.next();
	const original = throwing.c.state.step;
	s.check(original === "code", "on the code screen");
}

s.section("Test 12: what the screens say");
{
	const rig = makeRig({ bundled: true });
	const seen: Screen[] = [];
	const grab = (): void => { seen.push(buildScreen(rig.c)); };
	grab();
	await rig.c.next(); grab();
	rig.c.choosePath("new"); await tick(); grab();
	rig.c.chooseClient("own"); await tick();
	for (let i = 0; i < 5; i++) { grab(); await rig.c.next(); }
	grab();
	rig.c.setFieldByKey("clientId", OWN_ID);
	rig.c.setFieldByKey("clientSecret", OWN_SECRET);
	await rig.c.next(); grab();
	rig.c.setFieldByKey("passphrase", "a long passphrase");
	rig.c.setFieldByKey("passphraseConfirm", "a long passphrase");
	rig.c.setFieldByKey("riskAccepted", true);
	await rig.c.next(); grab();
	await rig.c.next(); grab();
	await rig.c.next(); grab();
	const ids = seen.map((x) => x.id);
	s.check(ids.join() === "welcome,choose,client,guide-project,guide-api,guide-consent,guide-client,guide-publish,paste,encryption,create,code,done", `screens seen (${ids.join()})`);
	const everything = JSON.stringify(seen);
	s.check(!/cloudflare|worker|wrangler/i.test(everything), "no Cloudflare wording anywhere in the wizard");
	s.check(seen.every((x) => x.buttons.filter((b) => b.kind === "primary").length <= 1), "at most one primary button per screen");
	s.check(seen.every((x) => x.title.length > 3), "every screen has a title");
	const urls = seen.flatMap((x) => x.body.flatMap((b) => (b.kind === "link" ? [b.url] : [])));
	s.check(urls.length >= 5 && urls.every((u) => u.startsWith("https://console.cloud.google.com/") || u === "https://www.google.com/device"), `every link goes to Google (${urls.length})`);
	s.check(urls.includes("https://console.cloud.google.com/apis/library/drive.googleapis.com") && urls.includes("https://console.cloud.google.com/auth/audience"), "the Drive API and Publish pages are linked");
	const text = (id: StepId): string => JSON.stringify(seen.find((x) => x.id === id)?.body ?? []);
	s.check(/TVs and Limited Input devices/.test(text("guide-client")), "the client type is named exactly");
	s.check(/Publish app/.test(text("guide-publish")) && /7 days/.test(text("guide-publish")), "publishing is explained, with the 7-day reason");
	s.check(/External/.test(text("guide-consent")), "the audience is named");
	s.check(/cannot be recovered/.test(JSON.stringify(seen.find((x) => x.id === "encryption"))), "the encryption screen warns that a lost passphrase cannot be recovered");
	s.check(/Do not paste it into a note inside this vault/.test(text("code")), "the code screen warns not to paste it into a note");
	s.check(/Keep this code private/.test(text("code")), "and to keep it private");
	s.check(!!(seen.find((x) => x.id === "paste")?.fields.some((f) => f.key === "clientSecret" && f.type === "password")), "the client secret is a password-style box");
	s.check(!!(seen.find((x) => x.id === "encryption")?.fields.filter((f) => f.type === "password").length === 2), "so are the passphrase boxes");
	s.check(allScreens(rig).length === 1, "(helper sanity)");
}

s.section("Test 13: createVault on its own");
{
	const drive = new FakeDrive();
	const seen: string[] = [];
	const steps = await createVault(drive.client(), { vaultId: "plainVaultXXXXXXXXXX", passphrase: "", onStep: (list) => seen.push(list.map((x) => x.status[0]).join("")) });
	s.check(steps.every((x) => x.status === "done"), "all steps done");
	s.check(seen.length >= 10 && seen[0]?.startsWith("r") === true, "progress is reported step by step");
	s.check(drive.calls.createFile === 2 && drive.calls.deleteFile === 1, "one test file written and removed, plus meta.json");
	const again = await createVault(drive.client(), { vaultId: "plainVaultXXXXXXXXXX", passphrase: "" });
	s.check(again.every((x) => x.status === "done") && drive.namesIn("YAOS plainVaultXXXXXXXXXX").join() === "meta.json", "running it again on the same vault is harmless");
	const bad = new FakeDrive();
	bad.failNext("readFile", 500, 1);
	let failed = false;
	try { await createVault(bad.client(), { vaultId: "plainVaultYYYYYYYYYY", passphrase: "" }); } catch (e) { failed = e instanceof DriveError; }
	s.check(failed, "a failing read stops it with the Drive error");
}

async function toHostedToken(rig: Rig): Promise<void> {
	await rig.c.next();
	rig.c.choosePath("new");
	await tick();
	rig.c.chooseClient("hosted");
	await tick();
}

s.section("Test 14: the easy sign-in, new vault");
{
	const rig = makeRig();
	await rig.c.next();
	rig.c.choosePath("new");
	await tick();
	const screen = buildScreen(rig.c);
	s.check(rig.c.state.step === "client", "the way to sign in is asked first");
	const primaries = screen.buttons.filter((b) => b.kind === "primary");
	s.check(primaries.length === 1 && primaries[0]?.action === "client-hosted", "the easy sign-in is the one highlighted choice");
	// Changed on purpose (2.1.1-drive.9): "Private sign-in" is the user's own Google client, not a "coming soon" placeholder.
	s.check(!screen.buttons.some((b) => b.action === "client-bundled"), "without a built-in client there is no disabled 'Private' placeholder");
	s.check(!/coming soon/i.test(JSON.stringify(screen)), "'coming soon' appears nowhere on the screen");
	const priv = screen.buttons.find((b) => b.action === "client-own");
	s.check(!!priv && priv.disabled !== true && /^Private sign-in \(your own Google client\)$/.test(priv.label), "'Private sign-in (your own Google client)' is a normal, pressable choice");
	s.check(screen.buttons.filter((b) => b.action === "client-hosted" || b.action === "client-own").length === 2, "exactly two ways to sign in are offered");
	s.check(/you create .*enter its client ID and secret yourself/i.test(JSON.stringify(screen.body)) && /details stay yours/.test(JSON.stringify(screen.body)), "the screen says the details are the user's own");
	s.check(/someone else|run by/i.test(JSON.stringify(screen.body)) && /never receives your notes/.test(JSON.stringify(screen.body)), "the screen says a third party is involved and that it never gets the notes");
	rig.c.chooseClient("hosted");
	await tick();
	s.check(rig.c.state.step === "hosted-token", "easy sign-in goes to the page for the code");
	s.check(buildScreen(rig.c).progress === "Step 4 of 9", `only nine steps (${String(buildScreen(rig.c).progress)})`);
	const page = buildScreen(rig.c);
	s.check(page.body.some((b) => b.kind === "link" && b.url === "https://ogd.richardxiong.com"), "a button opens the sign-in page");
	s.check(/run by the author of the Obsidian Google Drive plugin, not by YAOS/.test(JSON.stringify(page.body)) && /turn encryption on/.test(JSON.stringify(page.body)), "it says who runs the page and recommends encryption");
	s.check(page.fields.length === 1 && page.fields[0]?.type === "password", "the code goes into a hidden field");
	s.check(!rig.c.canNext(), "Next waits for a code");
	for (const [bad, part] of [["http://example.com", "web address"], ["short", "too short"], ["has space inside the code that is long enough", "no spaces"], ["YAOS-DRIVE1:abcdefghijklmnopqrstuvwxyz", "setup code"]] as const) {
		rig.c.setFieldByKey("hostedToken", bad);
		s.check(!rig.c.canNext() && String(rig.c.blocker()).includes(part), `refused: ${part}`);
	}
	rig.c.setFieldByKey("hostedToken", `  "${GOOD_TOKEN}"\n`);
	s.check(rig.c.canNext(), "quotes and spaces around a good code are tolerated");
	s.check(rig.httpCalls.length === 0 && rig.applied.length === 0 && rig.drive.calls.findFolders === 0, "nothing was sent anywhere yet");
	await rig.c.next();
	const sent = rig.httpCalls.filter((c) => c.url === HOSTED_URL);
	s.check(sent.length === 1, "the code is checked once with the sign-in service");
	const body = JSON.parse(sent[0]?.body ?? "{}") as Record<string, unknown>;
	s.check(body.refresh_token === GOOD_TOKEN && body.clientId === "" && body.clientSecret === "", "the request has the cleaned code and no client details");
	s.check(rig.httpCalls.every((c) => c.url === HOSTED_URL), "nothing was sent to anyone else");
	s.check(rig.signInCalls.length === 0, "Google's code sign-in is not used");
	s.check(rig.c.state.step === "encryption" && rig.drive.calls.findFolders === 0 && rig.applied.length === 0, "then encryption; still nothing saved or created");
	rig.c.setFieldByKey("passphrase", "a long passphrase");
	rig.c.setFieldByKey("passphraseConfirm", "a long passphrase");
	rig.c.setFieldByKey("riskAccepted", true);
	await rig.c.next();
	const patch = rig.applied[0];
	s.check(rig.applied.length === 1 && patch?.driveAuthMode === "hosted" && patch.driveRefreshToken === GOOD_TOKEN && patch.carrier === "drive", "saved with the easy sign-in marker and the cleaned code");
	s.check(patch?.driveClientId === "" && patch.driveClientSecret === "", "no client details are saved");
	s.check(rig.drive.namesIn(`YAOS ${FIRST_VAULT}`).join() === "meta.json", "the vault was created as usual");
	const code = rig.c.state.setupCode ?? "";
	s.check(code.startsWith("YAOS-DRIVE2:"), "the setup code is the easy-sign-in kind");
	const decoded = decodeSetupCode(code);
	s.check(decoded.ok && decoded.content.hosted === true && decoded.content.vaultId === FIRST_VAULT && decoded.content.passphrase === "a long passphrase" && decoded.content.clientId === "", "it carries the vault and passphrase but no client");
	s.check(!code.includes(GOOD_TOKEN) && !JSON.stringify(decoded).includes(GOOD_TOKEN), "and never the sign-in code");
	await rig.c.next();
	const codeScreen = buildScreen(rig.c);
	s.check(/sign in again on the same sign-in page/.test(JSON.stringify(codeScreen.body)) && /Keep this code private: it holds your vault ID and your passphrase/.test(JSON.stringify(codeScreen.body)), "the code screen explains the second device and does not talk about client details");
	await rig.c.next();
	s.check(rig.c.state.result === "started", "finished");
}

s.section("Test 15: the easy sign-in, problems and going back");
{
	const rig = makeRig();
	await toHostedToken(rig);
	rig.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	rig.hostedReply = { status: 400, json: { error: "invalid_grant", error_description: "Bad Request" } };
	await rig.c.next();
	s.check(rig.c.state.step === "signin" && /rejected the refresh token/.test(String(rig.c.state.error)), "a rejected code is explained");
	s.check(rig.applied.length === 0 && rig.c.state.draft.refreshToken === "", "nothing saved");
	s.check(buildScreen(rig.c).buttons.some((b) => b.action === "retry") && rig.c.canBack(), "Try again and Back are offered");
	rig.hostedReply = { status: 200, json: { access_token: "a", expires_in: 3600 } };
	await rig.c.retry();
	s.check(rig.c.state.step === "encryption" && rig.c.state.error === null, "Try again works once the service accepts it");
	const before = rig.httpCalls.length;
	await rig.c.back();
	s.check(rig.c.state.step === "hosted-token", "back from encryption lands on the code page, not the automatic step");
	await rig.c.next();
	s.check(rig.httpCalls.length === before && rig.c.state.step === "encryption", "going forward again does not ask the service a second time");
	await rig.c.back();
	rig.c.setFieldByKey("hostedToken", `${GOOD_TOKEN}-new`);
	await rig.c.next();
	s.check(rig.httpCalls.length === before + 1, "a changed code is checked again");

	const off = makeRig();
	await toHostedToken(off);
	off.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	off.hostedReply = "offline";
	await off.c.next();
	s.check(/No connection to the sign-in service/.test(String(off.c.state.error)) && off.applied.length === 0, "offline: a clear message, nothing saved");

	const down = makeRig();
	await toHostedToken(down);
	down.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	down.hostedReply = { status: 503, json: {} };
	await down.c.next();
	s.check(/temporary problem/.test(String(down.c.state.error)), "the service being down is called temporary");

	const cancelled = makeRig();
	await toHostedToken(cancelled);
	cancelled.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	cancelled.c.cancel();
	s.check(cancelled.closed === 1 && cancelled.applied.length === 0 && cancelled.drive.folders.size === 0 && cancelled.httpCalls.length === 0, "cancelling before pressing Next touches nothing");
}

s.section("Test 16: the setup code and joining with the easy sign-in");
{
	const first = makeRig();
	await toHostedToken(first);
	first.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	await first.c.next();
	first.c.setFieldByKey("passphrase", "a long passphrase");
	first.c.setFieldByKey("passphraseConfirm", "a long passphrase");
	first.c.setFieldByKey("riskAccepted", true);
	await first.c.next();
	const code = first.c.state.setupCode ?? "";

	const rig = makeRig({ drive: first.drive, settings: { vaultId: "someOtherVaultIdXXXXXXX" } });
	await rig.c.next();
	rig.c.choosePath("join");
	await tick();
	rig.c.setFieldByKey("setupCodeText", code);
	s.check(rig.c.previewJoinCode()?.hosted === true, "the preview knows it is an easy-sign-in code");
	s.check(/easy sign-in/.test(JSON.stringify(buildScreen(rig.c).body)), "and says so");
	await rig.c.next();
	s.check(rig.c.state.step === "hosted-token", "the second device is asked for its own sign-in code");
	s.check(rig.applied.length === 0 && rig.drive.calls.createFile === first.drive.calls.createFile, "nothing is saved yet");
	rig.c.setFieldByKey("hostedToken", `${GOOD_TOKEN}-device2`);
	await rig.c.next();
	s.check(rig.c.state.step === "join-check" && rig.c.state.joinCheck?.status === "ok", "the vault is found and the passphrase fits");
	s.check(rig.applied.length === 1 && rig.applied[0]?.driveAuthMode === "hosted" && rig.applied[0]?.driveRefreshToken === `${GOOD_TOKEN}-device2` && rig.applied[0]?.vaultId === FIRST_VAULT, "this device's own code and the vault are saved");
	s.check(rig.drive.namesIn(`YAOS ${FIRST_VAULT}`).join() === "meta.json", "joining wrote nothing to Drive");

	// a classic code still takes the classic route, even though 'easy' is the default
	const classic = makeRig();
	await createOwnVault(classic);
	const joinClassic = makeRig({ drive: classic.drive });
	await joinClassic.c.next();
	joinClassic.c.choosePath("join");
	await tick();
	joinClassic.c.setFieldByKey("setupCodeText", classic.c.state.setupCode ?? "");
	await joinClassic.c.next();
	s.check(joinClassic.c.state.step === "join-check" && joinClassic.signInCalls.length === 1 && joinClassic.httpCalls.length === 0 && joinClassic.applied[0]?.driveAuthMode === undefined, "an older-style code signs in with Google's code, never asks for a sign-in code, and saves no easy marker");

	// by hand
	const hand = makeRig({ drive: first.drive });
	await hand.c.next();
	hand.c.choosePath("join");
	await tick();
	hand.c.setFieldByKey("manualJoin", true);
	hand.c.setFieldByKey("vaultId", FIRST_VAULT);
	hand.c.setFieldByKey("passphrase", "a long passphrase");
	s.check(!hand.c.canNext(), "by hand without a client or the easy box: Google details are required");
	hand.c.setFieldByKey("joinHosted", true);
	s.check(hand.c.canNext() && !buildScreen(hand.c).fields.some((f) => f.key === "clientId"), "with the easy box ticked the Google fields disappear");
	await hand.c.next();
	s.check(hand.c.state.step === "hosted-token", "then it asks for the sign-in code");
	hand.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	await hand.c.next();
	s.check(hand.c.state.joinCheck?.status === "ok" && hand.applied[0]?.driveAuthMode === "hosted", "joined by hand");
}

s.section("Test 17: a device that is already set up, then the easy sign-in");
{
	const rig = makeRig({
		settings: { carrier: "drive", vaultId: "existingVaultIdXXXXXXXX", driveClientId: OWN_ID, driveClientSecret: OWN_SECRET, driveRefreshToken: "old" },
		vaultIds: ["brandNewVaultIdYYYYYYYY"],
	});
	await toHostedToken(rig);
	s.check(rig.c.state.step === "existing", "the warning comes first");
	rig.c.setFieldByKey("existingAccepted", true);
	await rig.c.next();
	s.check(rig.c.state.step === "hosted-token", "then the sign-in code");
	rig.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	await rig.c.next();
	rig.c.setFieldByKey("encrypt", false);
	await rig.c.next();
	s.check(rig.applied[0]?.driveClientId === OWN_ID && rig.applied[0]?.driveClientSecret === OWN_SECRET, "the earlier client details are kept, not erased");
	s.check(rig.applied[0]?.driveAuthMode === "hosted" && rig.applied[0]?.vaultId === "brandNewVaultIdYYYYYYYY", "new vault, easy sign-in");

	// private path stays available when a built-in client exists
	const withBuiltin = makeRig({ bundled: true });
	await withBuiltin.c.next();
	withBuiltin.c.choosePath("new");
	await tick();
	const choice = buildScreen(withBuiltin.c).buttons.find((b) => b.action === "client-bundled");
	s.check(!!choice && choice.disabled !== true && !/coming soon/i.test(choice.label), "with a built-in client the private choice is available");
	withBuiltin.c.chooseClient("bundled");
	await tick();
	s.check(withBuiltin.signInCalls.length === 1 && withBuiltin.httpCalls.length === 0 && withBuiltin.c.state.step === "encryption", "and it uses Google's code sign-in only");
	s.check(withBuiltin.applied.length === 0, "(nothing saved yet)");
	withBuiltin.c.setFieldByKey("encrypt", false);
	await withBuiltin.c.next();
	s.check(withBuiltin.applied[0]?.driveAuthMode === undefined && !("driveAuthMode" in (withBuiltin.applied[0] ?? {})), "the private path never sets the easy marker");

	// no wording about Cloudflare anywhere on the new screens
	const words = makeRig();
	await toHostedToken(words);
	const all = JSON.stringify([buildScreen(words.c)]);
	s.check(!/cloudflare|worker|wrangler/i.test(all), "the new screens have no Cloudflare wording");
}

s.section("Test 18: hosted configuration failure and replacing rejected tokens");
{
	const rig = makeRig();
	await toHostedToken(rig);
	rig.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	rig.hostedReply = { status: 400, json: { error: "invalid_client", error_description: GOOD_TOKEN } };
	await rig.c.next();
	s.check(/configuration problem/.test(String(rig.c.state.error)) && !String(rig.c.state.error).includes(GOOD_TOKEN), "configuration failures have safe hosted-specific guidance");
	s.check(rig.applied.length === 0 && rig.drive.folders.size === 0 && rig.c.state.draft.hostedToken === GOOD_TOKEN, "failure keeps input and touches no settings or Drive files");
	rig.hostedReply = { status: 400, json: { error: "invalid_grant" } };
	await rig.c.retry();
	s.check(/Try again resends the same token/.test(String(rig.c.state.error)), "rejection explains retry semantics");
	await rig.c.back();
	s.check(rig.c.state.step === "hosted-token", "Back returns to token replacement");
	rig.c.setFieldByKey("hostedToken", `${GOOD_TOKEN}-replacement`);
	rig.hostedReply = { status: 200, json: { access_token: "ok" } };
	await rig.c.next();
	s.check(rig.c.state.step === "encryption" && rig.c.state.draft.refreshToken.endsWith("-replacement"), "replacement token succeeds without restarting wizard");
	s.check(rig.applied.length === 0 && rig.drive.folders.size === 0, "validation success alone still saves and creates nothing");
}

s.section("Test 19: wizard uses saved endpoint and revalidates endpoint changes");
{
	const custom = "https://custom.test/api/access?private=query-secret";
	const rig = makeRig({ savedEndpoint: true, settings: { driveHostedUrl: ` ${custom} ` } });
	await toHostedToken(rig);
	const body = JSON.stringify(buildScreen(rig.c).body);
	s.check(body.includes("https://custom.test") && !body.includes("query-secret"), "custom destination is disclosed without query secrets");
	rig.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	await rig.c.next();
	s.check(rig.c.state.step === "encryption" && rig.httpCalls.length === 1 && rig.httpCalls[0]?.url === custom, "saved endpoint is used without a test URL override");
	await rig.c.back();
	rig.settings.driveHostedUrl = "https://second-custom.test/api/access";
	await rig.c.next();
	s.check(rig.httpCalls.length === 2 && rig.httpCalls[1]?.url === rig.settings.driveHostedUrl, "endpoint change invalidates cached sign-in identity");
	s.check(rig.httpCalls.every((call) => call.url !== "https://ogd-server.richardxiong.com/api/access"), "no token is sent to the default service as a fallback");
}

s.section("Test 20: custom endpoint is also used during vault lookup");
{
	const endpoint = "https://private-token-service.test/access";
	const rig = makeRig({ savedEndpoint: true, realApi: true, settings: { driveHostedUrl: ` ${endpoint} ` } });
	await toHostedToken(rig);
	rig.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	await rig.c.next();
	await rig.c.runJoinCheck();
	const tokenCalls = rig.httpCalls.filter((call) => call.url === endpoint);
	s.check(tokenCalls.length === 2, "both validation and actual Drive API token refresh use saved endpoint");
	s.check(rig.httpCalls.some((call) => call.url.startsWith("https://www.googleapis.com/drive/v3/files")), "vault lookup still goes directly to Google");
	s.check(rig.httpCalls.every((call) => call.url === endpoint || call.url.startsWith("https://www.googleapis.com/drive/v3/files")), "no default-service fallback during vault lookup");
	s.check(rig.applied.length === 0, "missing vault does not save settings");
}

s.section("Test 21: cancellation ignores an in-flight hosted response");
{
	const rig = makeRig();
	await toHostedToken(rig);
	rig.c.setFieldByKey("hostedToken", GOOD_TOKEN);
	let release = () => {};
	const promise = new Promise<void>((resolve) => { release = resolve; });
	rig.gate = { promise, release };
	const pending = rig.c.next();
	await tick();
	rig.c.cancel();
	release();
	await pending;
	s.check(rig.closed === 1 && rig.c.state.draft.refreshToken === "" && rig.c.state.step === "signin", "cancelled hosted success cannot advance or retain verified credentials");
	s.check(rig.applied.length === 0 && rig.drive.folders.size === 0, "cancelled hosted validation touches neither settings nor Drive");
}

await s.done();
